---
version: 2.1

orbs:
  win: circleci/windows@2.4.0

jobs:
  linux-gcc:
    machine:
      image: ubuntu-1604:201903-01
    steps:
      - checkout
      - run:
          name: Install Software
          command: |
            sudo apt-get update
            sudo apt-get install -y build-essential
            ./autogen.sh
            ./configure
            make build-dep
            make
workflows:
  version: 2
  run-all:
    jobs:
      - linux-gcc
